name: test_code
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  pin_code_fields: ^8.0.1
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.9.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
